# logging config
logging:
  level:
    org.springframework.web: TRACE
    org.springframework.http: TRACE
    reactor.core: TRACE
    io.netty: TRACE

# spring config
spring:
  main:
    web-application-type: none

twitter.api-key: ${TWITTER_BEARER_TOKEN}